version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ranktracker
      POSTGRES_USER: rthorslev
      POSTGRES_PASSWORD: "#Er45r5rpopo!123"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ranktracker:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: