# Generated by Django 5.2.6 on 2025-09-22 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_alter_keyword_name_alter_rankresult_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='client',
        ),
        migrations.RemoveField(
            model_name='rankresult',
            name='client',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rankresult',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.keyword'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
