# Generated by Django 5.2.6 on 2025-09-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_alter_keyword_name_alter_rankresult_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='client',
        ),
        migrations.RemoveField(
            model_name='rankresult',
            name='client',
        ),
        migrations.AddField(
            model_name='keyword',
            name='clients',
            field=models.ManyToManyField(related_name='keywords', to='core.client'),
        ),
    ]
